services:
  fastapi-service:
    build: .
    container_name: ai
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - LOG_LEVEL=DEBUG
      - TZ=UTC
    volumes:
      - ./logs:/app/logs
    # Если нужно GPU
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:  
    #         - driver: nvidia 
    #           count: all
    #           capabilities: [gpu]
